chore: add `jq` to hermetic build image definition (#2539)
From
https://github.com/diegomarquezp/google-cloud-java/actions/runs/8178920720/job/22363860250

```
+ /usr/local/lib/python3.11/site-packages/library_generation/owlbot/bin/write_clirr_ignore.sh /usr/local/lib/python3.11/site-packages/library_generation
/workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1 /workspace/google-cloud-java/java-datastore
/workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1/src/main/java /workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1 /workspace/google-cloud-java/java-datastore
/usr/local/lib/python3.11/site-packages/library_generation/owlbot/bin/write_clirr_ignore.sh: line 29: jq: command not found
Library postprocessing failed
Error: Process completed with exit code 1.
```

This PR adds jq to the docker image

## Cause
`write_clirr_ignore` only acts on the repo whenever there is no
clirr_ignored_differences found. This occurs when generating a new
library from scratch, and we've only testing against existing libraries
(i.e. we didn't reach this call to `jq` in any of our previous testing).


https://github.com/googleapis/sdk-platform-java/blob/3ed98b1b84b4694fb0268c28e01dfcd21e484b59/library_generation/owlbot/bin/write_clirr_ignore.sh#L24-L29