ci: correct working-directory in sdk-platform-java-verify_library_generation.yaml (#12346)
sdk-platform-java-verify_library_generation.yaml has been failing due to
the following errors

```
+ pip install --require-hashes -r hermetic_build/common/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'hermetic_build/common/requirements.txt'
Error: Process completed with exit code 1.
```

Add sdk-platform-java as working-directory to make sure the scripts runs
against the correct folder.