ci: Run all downstream protobuf CI checks with Java 8 JVM (#3747)
Error:
```
Error: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/cloud/datastore/emulator/CloudDatastore has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This error seemed to show up ~3 weeks ago, but it doesn't look like
anything changed in java-datastore. Cloud Datastore Emulator seems to
have required JRE 11 since ~late 2022. We have been compiling with JDK
11 and running with Java 8.

Successful run:
https://github.com/googleapis/sdk-platform-java/actions/runs/14522553161