chore: run fmt command on java-dataplex (#12317)
This PR fixes lint issues with java-dataplex that are blocking [spanner
PR](https://github.com/googleapis/google-cloud-java/pull/12293)

The [lint check on spanner
PR](https://github.com/googleapis/google-cloud-java/actions/runs/23763214864/job/69235942554?pr=12293)is
failing due to:

```
Error:  Failed to execute goal com.spotify.fmt:fmt-maven-plugin:2.25:check (default-cli) on project grpc-google-cloud-dataplex-v1: Found 1 non-complying files, failing build -> [Help 1]
```