fix: graalvm missing build time class when using protobuf 4.x (#3438)
In case of protobuf 4+ need to include protobuf.Runtime in classes
initialized at build time as that is used to determine protobuf version
for graalvm.

Tested, temporarily bumped protobuf dependency to 4.28.1 without
including Runtime in build time class list. Received error:

```
Error: Classes that should be initialized at run time got initialized during image building:
 com.google.protobuf.RuntimeVersion was unintentionally initialized at build time. To see why com.google.protobuf.RuntimeVersion got initialized use --trace-class-initialization=com.google.protobuf.RuntimeVersion
```

Updated to include Runtime and received passing [native showcase
tests](https://github.com/googleapis/sdk-platform-java/actions/runs/12205342463/job/34052473211?pr=3438)