chore: follow up fix to verify_library_generation (#2721)
https://github.com/googleapis/sdk-platform-java/pull/2716 didn't quite
fix what it should have. Follow up to fix the error:

```
Previous HEAD position was e54601fce Merge 30c7c5b4f9825c14458d6ef31e0b3e3fccbb4207 into e7231131d94da44c91cd6aeeb526076bcc51db46
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
+ git fetch --no-tags --prune origin +main:refs/remotes/origin/main
From https://github.com/googleapis/sdk-platform-java
 - [deleted]             (none)     -> origin/main
+ git checkout renovate/markupsafe-2.x
error: pathspec 'renovate/markupsafe-2.x' did not match any file(s) known to git
```

---------

Co-authored-by: Joe Wang <106995533+JoeWang1127@users.noreply.github.com>